### ISSUE TITLE
Expose Conflict errors and allow wrapping get/replace with backoff

### ISSUE THREAD

**Issue by clux** [kube-rs/kube-rs#34]
client-go encourages [RetryOnConflict](https://godoc.org/k8s.io/client-go/util/retry#RetryOnConflict) which is a reasonable pattern - [code's also not that advanced](https://github.com/kubernetes/client-go/blob/master/util/retry/util.go).

Rust has:
- [backoff](https://github.com/ihrwein/backoff/blob/master/examples/retry.rs)
- [retry](https://docs.rs/retry/0.5.0/retry/) - with [tokio version](https://docs.rs/tokio-retry/0.2.0/tokio_retry/)

We could probably make wrappers around that..

AFAIKT it's just a wrapper around a deliberate error match case, where the backoff continues. That should be easy to emulate now that we've exposed api error helpers on our `Error` type. Backoff seems like a good fit atm.

**Comment by clux** [comment]
https://docs.rs/backoff/0.2.1/backoff/future/fn.retry.html looks pretty nice now. Want to get this into one of the bigger examples and close this.

**Comment by clux** [comment]
Actually, I guess the key point here is to figure out where to use this. If we just put retry inside the reconciliation loop it wouldn't matter much, because that kind of has backoff built in.

However, as the go side lets you wrap a `RetryOnConflict` to retry the `get` + `replace` until it works. That should be less of an issue with server side apply. Still, a util that wraps `Api::replace` with something like that might be useful.

**Comment by teozkr** [comment]
IMO the "obvious" place to put this would be to provide it as an `error_policy` helper. The current controller machinery isn't well-suited for long-running reconcilers, since that would block reconciling for all watched objects, not just that one. The main problem then would be to have a good way to associate the `controller::Error` back to the `ObjectRef`, but that would be nice to have regardless.

**Comment by teozkr** [comment]
Maybe consider also adding backoff to `watcher`, actually..

**Comment by kazk** [comment]
Maybe try [`RetryLayer`](https://docs.rs/tower/0.4.8/tower/retry/struct.RetryLayer.html)? It's per request and [`Policy`](https://docs.rs/tower/0.4.8/tower/retry/trait.Policy.html) looks flexible (return `Option<Future<Policy>>` based on request/response).

**Comment by clux** [comment]
Oh, that's nice! We could even use the `Policy` to do error matching and globally set `RetryOnConflict` equivalents if we modified `Api::replace` methods to optionally do a .get right before to get the latest resource version.

**Comment by teozkr** [comment]
> Maybe try RetryLayer? It's per request and Policy looks flexible (return Option<Future<Policy>> based on request/response).

Isn't the layer stack decided when building the `Client`, IIRC?

This needs cooperation from the user code, since only the user knows what exact changes were made, and why. At the very least, you'd need to replace the current `Api<K>::replace(new: K)` with a `Api<K>::update(mutate: impl FnMut(K) -> K)`, which could call `mutate` on every conflict.

> We could even use the Policy to do error matching and globally set RetryOnConflict equivalents if we modified Api::replace methods to optionally do an Api::get right before to get the latest resource version.

If you want to steamroll the conflicts (which is the only thing that we can do with our current API) then you don't need any of this machinery anyway; just set `resource_version` to `None`.

In order to actually handle the conflicts, you need to understand the mutation. For example, with `Controller` you'd let it crash and retry the whole reconciliation. I'm not saying `Controller` is right for every use case, but I think that's roughly the level where you'd need to hook in conflict resolution in any case.

---

Of course, there are still transient errors that do warrant transparent retries (network errors, and so on). But it's important that we don't get overzealous.

**Comment by kazk** [comment]
Yeah, sorry, I didn't understand the requirements and the `Policy` trait correctly. We can't use `RetryLayer` for this. (`RetryLayer` can be used for other retries, though. e.g., retrying `GET` requests on `Retry-After` response like client-go.)

> This needs cooperation from the user code, since only the user knows what exact changes were made, and why.

Yeah, I thought users can provide their `Policy` when creating a client used by the controller. But that `Policy` won't have enough information to do what we want, and the trait doesn't allow it either.

**Comment by clux** [comment]
Going to close this. It's not worth doing anything smart for get/replace now that server-side apply is ubiquitous.

The way to do this for individual calls is using [`backoff::future::retry`](https://docs.rs/backoff/0.3.0/backoff/future/fn.retry.html). Based on the [error type](https://docs.rs/backoff/0.3.0/backoff/enum.Error.html) you set there, it will either retry (for a configurable amount of time/times), or bubble up the error.

Watcher has a similar `backoff_watch` system (via #577 ) that also uses the same `backoff` library.
