### ISSUE TITLE
Example of using `jsonpath` or `field-selector` flags

### ISSUE THREAD

**Issue by Dentrax** [kube-rs/kube-rs#489]
I'm just getting used to this library. One thing that confuses me is how to send a request using `jsonpath` or `field-selector` flags. I could not find enough information on either how to use it or it's already supported. [(search)](https://github.com/clux/kube-rs/search?q=jsonpath)

How do I build an equivalent kube-rs request to this command using this library?

* _jsonpath_:
```bash
$ kubectl get pods -o=jsonpath='{range .items[*]}{.metadata.name}'
```

* _--field-selector_:
```bash
$ kubectl get pods --field-selector status.phase=='Running'
```

**Comment by clux** [comment]
For the `--field-selector` equivalent, you can set the field selector string in [`ListParams`](https://docs.rs/kube/0.52.0/kube/api/struct.ListParams.html), although it's not something we have examples of atm, you should be able to just set the string to `Some("status.phase=='Running'".to_string())`.

Though you can always cross reference with `kubectl -v=9` when you make the query and look for the `curl` line if you have difficulties constructing the `ListParams` (but know that the parameters you pass in will be url encoded by kube).

For `-o jsonpath`, that's a `kubectl`-ism that we don't have support for (because it's basically running something like `jq` to grab particular fields of the data after the query has been done). It's potentially something we could support because we already have a `jsonpath_lib` that can do querying. If there's interest into it, I am happy to discuss what that feature could look like more.

**Comment by Dentrax** [comment]
Thanks for the prompt reply and detailed explanation. I'd like to try this as soon as I have some free time. 

> ...although it's not something we have examples of atm...

Also, I'd like to send a PR that introduces new `ListParams` examples, If I can achieve something successfully. I'll ping you here about the situation.

> It's potentially something we could support because we already have a jsonpath_lib that can do querying.

Yep, that would be great.

**Comment by MikailBag** [comment]
If the desired path is known statically, it can easier to use typed API, because you have no chance to use wrong field path:

```rust
let pods_api = Api::<Pod>::namespace(client.clone(), ns);
let pods = pods.list().await?;
for pod in pods {
    println!("{}", pod.name());
}
```

But `kube` also provides dynamic API that can be used to achieve something similar to `kubectl get --field-selector ... -ojsonpath=...`. [This](https://gist.github.com/MikailBag/89b99cf2c5efae25bdf247c2c0f0a0e2) gist (based on [`dynamic_watcher` example](https://github.com/clux/kube-rs/blob/master/examples/dynamic_api.rs)) shows how you can apply arbitrary JSON paths to arbitrary resources matching arbitrary field selector.

**Comment by clux** [comment]
That looks great, and easy. Perhaps the main thing we ought to do on `jsonpath` is simply document `DynamicObject` with an example on how to do `jsonpath_lib` querie on the resulting `serde_json::Value`.

**Comment by clux** [comment]
Changed the title of this and labels. The only thing we want out of this is an example that showcases doing this with the dynamic api. It's probably not too bad for a first contributor to try to tackle:

- adapt the `dynamic_watcher` example but remove the last watcher part
- use the `Api<DynamicObject>` to do an `api.list()`
- use the `jsonpath_lib` to query the underlying `serde_json::Value` objects with an arbitrary query from the `std::env`
