### ISSUE TITLE
CRDs for multiple resource versions

### ISSUE THREAD

**Issue by cassandracomar** [kube-rs/kube-rs#569]
currently, we can use this crate to generate a CRD for a single version of a struct/resource. but as code moves into production, we need to be able to support multiple versions of a single struct, with separate definitions hidden behind qualified versions -- e.g. `v1alpha1::MyResource`, `v1beta1::MyResource`, etc.. this allows released versions of the api to continue to be supported for a duration until deprecation and finally removal. also, one version of the struct must be selected for storage by the k8s api server. additionally, we should be able to specify that a particular version of a resource is deprecated.

one option is to add a new field to the `CustomResource` macro to allow specifying other versions of the struct. then, the version of the struct selected by the end user to generate the final, installed CRD can be chosen as the primary version of the `CustomResource` for storage. alternatively, we could set up a new macro to produce a CRD from multiple types implementing `CustomResource` with the same group and kind.

the main way we see this being used is by separating resource definitions into module paths that follow the group/version/kind hierarchy. then all versions with a given group/kind can be specified with qualification by consumers that care about the multiple versions of a resource, including the `CustomResource` derive macro.

I'm happy to send a PR for this in the coming weeks, just want to collect some thoughts on how best to approach this before I do, however.

**Comment by teozkr** [comment]
I don't think this would require a macro, it should be possible to write a helper to merge the CRD objects in plain ol' Rust with the information that we already expose.

Client code would typically only care about one version anyway, and let the K8s conversion machinery take care of the rest.

One thing that would be a bit tricky would be handling upgrades, but I think that would be out of scope for the MVP.

**Comment by clux** [comment]
I'm curious about both of the suggested solutions here; i.e. a plain rust solution and a derive attr based one.

A `#[kube]` attr based one is interesting if it's only for selecting the main `FooSpec` struct. That could be workable, and linked with a version (whereas field level attrs would probably be a nightmare). Although not sure how the derive macro can refer to two different structs easily?

I can also imagine this __could__ be done on the user side with the required modularity; something that invokes identical `#[kube(attr..)]`  (but different `#[kube(version = X)]`) around two different structs, but that is possibly difficult due to all the macros involved? Having a hard time imagining a `fn make_crd<K>(version: String)` compiling.

Anyway, a best-practice solution would be welcome and reviewed regardless!

**Comment by bestgopher** [comment]
@clux Maybe `#[kube(storageversion="v1")]` to specify the version？

**Comment by clux** [comment]
Maybe, but it would need other mechanisms to form a complete solution.

Thinking about it some more: we need to end up with a [`CustomResourceDefinition`](https://docs.rs/k8s-openapi/latest/k8s_openapi/apiextensions_apiserver/pkg/apis/apiextensions/v1/struct.CustomResourceDefinition.html) containing multiple [`CRDVersion`](https://docs.rs/k8s-openapi/latest/k8s_openapi/apiextensions_apiserver/pkg/apis/apiextensions/v1/struct.CustomResourceDefinitionVersion.html) objects on its spec only one of which can set the `storage` bool to `true`.

We could extend `kube-derive` with `storageversion` and maybe allow specifying `struct` per version so they can point at different structs, but that's a lot of complexity in kube-derive and it feels like an awkward and possibly impossible derive api (currently struct names are implied by what we derive on).

If users instead have folders for each api / derived structs:

- myapp/src/v1/derive.rs (structs for mycrd.mygroup v1)
- myapp/src/v2/derive.rs (structs for mycrd.mygroup v2) - sets new `#[kube(served = false)]` 
- myapp/src/v3/derive.rs (structs for mycrd.mygroup v3beta1)

then we can provide a merge fn that takes the `::crd` output of each of these independently, verifying that they are compatible (same GVK, names, webhooks).

It means a bit of duplication of derive attributes from [the global spec properties](https://docs.rs/k8s-openapi/latest/k8s_openapi/apiextensions_apiserver/pkg/apis/apiextensions/v1/struct.CustomResourceDefinitionSpec.html) that we have to verify, but i think that's fine given that multi-versioning is clearly not our major use case (very little action on this issue).

This was Teo's original idea in the comment above (i think), this is just expanding on it. I think this is the right way forward.

**Comment by clux** [comment]
It's kind of not too hard to do all this either;

### kube-core/src/crd.rs
either a simple merge fn:

```rust
pub fn crd::CustomResourceExt::merge(crds: &[CustomResourceDefinition]) -> Result<CustomResourceDefinition, Error> { todo!() }
```
with some new error type validating crd vectors all have same global properties
but this is slightly problematic because it means you cant change global properties unless you change all at the same time

so probably better to have some sort of builder in crd.rs:

```rust
pub struct CustomResourceMerger {}
```
that can be constructed with:

```rust
CustomResourceMerger::new(crds: Vec<CustomResourceDefinition>).served("v2").globals("v3beta1")
```

this allows us to specify:
-`served` bool outside (and avoids having an implicit `true` default in kube-derive)
- a version to take the the webhook properties, names, preserve bools from (latest might make sense for globals?)
