### ISSUE TITLE
`make k3d` should be k3d version agnostic

### ISSUE THREAD

**Issue by ChinYing-Li** [kube-rs/kube-rs#759]
### Would you like to work on this feature?

yes

### What problem are you trying to solve?

The current makefile command `k3d`: 
```bash
k3d cluster create --servers 1 --agents 1 main \
		--k3s-agent-arg '--kubelet-arg=eviction-hard=imagefs.available<1%,nodefs.available<1%' \
		--k3s-agent-arg '--kubelet-arg=eviction-minimum-reclaim=imagefs.available=1%,nodefs.available=1%'

```
Only works for `k3d` version 4.4.8;
`k3d` version 5.0.0 + no longer has the `--k3s-agent-arg` flag.

### Describe the solution you'd like

Would be best to have a doc that details the commands for creating k3d cluster with specific version of `k3d`. I can help with this if needed.

### Describe alternatives you've considered

Alternatively, we can have two sets of `k3d*` commands e.g. `make k3d5` and `make k3d4`, where the suffices 5 and 4 correspond to the k3d version. `k3d4` should be like this: 
```bash
k3d cluster create --servers 1 --agents 1 main \
		--k3s-arg "--kubelet-arg=eviction-hard=imagefs.available<1%,nodefs.available<1%@agent:*" \
		--k3s-arg "--kubelet-arg=eviction-minimum-reclaim=imagefs.available=1%,nodefs.available=1%@agent:*"
```

**Comment by clux** [comment]
Ah, yes, thank you. We definitely should upgrade it to `k3d` 5. It's probably not necessary for this project to maintain a bunch of k3d 4 vs k3d 5 compat things (our CI is k3d 5).

The function I got to work locally with local testing was:

```sh
 k3d cluster create main --servers 1 --agents 1 --registry-create main \
  --k3s-arg "--no-deploy=traefik@server:*" \
  --k3s-arg '--kubelet-arg=eviction-hard=imagefs.available<1%,nodefs.available<1%@agent:*' \
  --k3s-arg '--kubelet-arg=eviction-minimum-reclaim=imagefs.available=1%,nodefs.available=1%@agent:*'
k3d kubeconfig get --all > ~/.kube/k3d
```
because of a small disk, want it to be fast even on a laptop, and have a bunch of kubeconfigs that i smash together with `export KUBECONFIG="$(fd . ~/.kube --max-depth 1 --type f | paste -s -d':')"` in my `.bash_profile`

but it's probably not super useful to expose all of that to the user, so might just take the cluster create part and put that in there.
