### ISSUE TITLE
Controller: Get Access to ReconcileReason

### ISSUE THREAD

**Issue by theduke** [kube-rs/kube-rs#800]
### Would you like to work on this feature?

probably

### What problem are you trying to solve?

Unless I'm missing something, there currently doesn't seem to be a way to access `ReconcileReason` in the `reconcile` callback.

That's important for knowing what actually changed, and what to do about it.

### Describe the solution you'd like

The `Controller::run`  `reconcile` callback should probably look like `impl FnMut(Arc<K>, reason: ReconcileReason, Context<T>) -> ReconcilerFut`.

### Describe alternatives you've considered

n/a

### Target crate for feature

kube-runtime

**Comment by teozkr** [comment]
This is an intentional design choice. `ReconcileReason` only tells you why the reconciliation was started, not what needs to be done to fix it. It's only meant as an aid to help you get out of infinite reconciliation loops.

> That's important for knowing what actually changed, and what to do about it.

You always need to do a full cluster inspection to see what needs to be done. If that's too expensive then you should consider caching via a `reflector` (and arguably we should do a better job in assisting this caching for owned objects and the like).

Why?

1. We deduplicate reconciliation requests, so that there is at most one running and one pending reconciliation per object per `Controller`(/`applier`). If (non-trivial) reconciliations are triggered in short succession due to reasons X, Y, and Z then `reconcile(obj, X)` will start running immediately, `reconcile(obj, Y)` will be scheduled for when X is done, and Z will be dropped (since Y is already pending). Any logic that depends on observing a difference between Y and Z would be broken here.
2. Events may be lost, for example due to the controller restarting, or a connection issue to the cluster.

**Comment by theduke** [comment]
I see, that makes sense.

> and arguably we should do a better job in assisting this caching for owned objects and the like

My specific issue is exactly the owned resource case.
I guess I can use `applier` to prevent a second redundant watcher.

**Comment by teozkr** [comment]
Yeah, for now I'd drop down to `applier` for that use case.

Closing this as a WONTFIX then.
