### ISSUE TITLE
Potential deadlock in SpitCase impl Stream

### ISSUE THREAD

**Issue by clux** [kube-rs/kube-rs#930]
interesting [new clippy lint](https://rust-lang.github.io/rust-clippy/master/index.html#significant_drop_in_scrutinee) seems to suggest that `impl Stream for SplitCase` can deadlock (rust issue: https://github.com/rust-lang/rust/issues/93883 ).

this is used in applier.

haven't had time to look at it fully, but it looks similar to our setup, and it blocks ci atm.

clippied code shows `this.inner` being locked
https://github.com/kube-rs/kube-rs/blob/98cf1c89c37bb8bfc12b0d31d0b3264b13076771/kube-runtime/src/utils/mod.rs#L78-L97

**Comment by teozkr** [comment]
Whoa, that's a thoroughly unhelpful error message.. :/

I don't *think* we have an issue here, since the temporaries involved here are:

1. `inner.as_mut()`: just a "dumb" projection of `inner`, misuse is protected against since it grabs a mut borrow on `inner` for its lifetime
2. `poll_next()`: stateful and complex, but the return value is "just" the ADT `Poll<Option<S::Item>>`

`Poll` and `Option` are both just dumb data and I don't see any `has_significant_drop` attribute on `Pin`, so I can only assume that it assumes the worst for `S::Item`?
