### ISSUE TITLE
Missing apiVersion and kind on Event::Restarted when using DynamicObject

### ISSUE THREAD

**Issue by goenning** [kube-rs/kube-rs#946]
### Current and expected behavior

When using the `watcher` and `Api<DynamicObject>`, the resources returned by `Event::Restarted` does not have apiVersion and kind, they only include metadata/spec/status.

If I apply a change via kubectl, the `Event::Applied` returns that resource and it does include apiVersion and kind.

If I change to `Api<Deployment>`, then it returns apiVerion/kind on both Restarted and Applied.

I expect the apiVersion and kind to always be present on both Restarted and Applied, when using DynamicObject.

### Possible solution

I have no idea, i'm pretty new to Rust so I'm having a hard time navigate the codebase.

### Additional context

```rust
    let lp = ListParams::default();
    let api: Api<DynamicObject>;
    let apigroup = discovery::group(&client, &api_group)
        .await
        .map_err(|e| e.to_string())?;

    let (ar, _caps) = apigroup.recommended_kind(&resource).unwrap();

    if namespace.is_empty() {
        api = Api::all_with(client, &ar);
    } else {
        api = Api::namespaced_with(client, &namespace, &ar);
    }

    let handle = tauri::async_runtime::spawn(async move {
        let w = watcher(api, lp);

        pin_mut!(w);

        loop {
            let event = w.try_next().await;

            match event {
                Ok(Some(Event::Applied(e))) => ...  // here, `e` contains a single resource WITH apiVersion/kind
                Ok(Some(Event::Deleted(e))) => ...
                Ok(Some(Event::Restarted(e))) => ... // here, `e` contains an array of resources WITHOUT apiVersion/kind
                Ok(None) => ...
                Err(err) => ...
            }
        }
    });
```

### When using `Api<DynamicObject>`

<img width="736" alt="Screen Shot 2022-07-01 at 21 41 58" src="https://user-images.githubusercontent.com/94755/176966388-9363e9f7-848b-4fb5-ba61-e6b5632c36aa.png">

### When using `Api<Deployment>`

<img width="692" alt="Screen Shot 2022-07-01 at 21 44 22" src="https://user-images.githubusercontent.com/94755/176966482-b2468671-189b-4500-844e-8687b7fb746d.png">

### Environment

Minikube 1.24.1
macOS Monterrey

Note: the code is running on my local machine, not inside k8s

### Configuration and features

```toml
kube = { version = "0.73.1", features = ["client", "runtime"]  }
k8s-openapi = { version = "0.15.0", features = ["v1_24"] }
```

### Affected crates

kube-client, kube-runtime

### Would you like to work on fixing this bug?

maybe, but I'd need a lot of help :)

**Comment by goenning** [comment]
Looks like this is exactly an API Server behaviour https://github.com/kubernetes/kubernetes/issues/3030

Quite a few people (myself included) expected these properties to be set.

kube-rs backfill those? For now I'm doing it on my end, but I'll leave the issue here in case The maintainers think this would be a good addition, but it's certainly not a bug

**Comment by teozkr** [comment]
Hm, the situation certainly sucks. I agree that it's a bug (and the upstream Kube people seem to agree), but I'm not sure if it's our place to work around this. Ideally someone would take https://github.com/kubernetes/kubernetes/pull/63972 and get that into a shippable state.

**Comment by clux** [comment]
Yeah, this does very much feel like upstream should fix it rather than us patching returned objects from the apiserver. It feels counterproductive for us to do it because it helps mask the need for a proper fix elsewhere, and it pollutes our api with unneeded methods.

Why is it unneeded? The `watcher` should always return objects of the same type, so all the data is right there on the `ar: ApiResource` (either directly or through the `ResourceExt` trait), so the data can be passed around there for small cases. For more complex situations where it's impractical to pass the `ApiResource` around, you can run a `map_ok` on the `watcher` stream where it's created to fill in the information from `ar`. Similar example is found in the `pod_reflector` example:

https://github.com/kube-rs/kube-rs/blob/3cab1787f45a7ffdf7c495b4b2c770de96077328/examples/pod_reflector.rs#L31-L38

Think this is probably a `wontfix`. Thanks for the report though!
